search:-
write('!!!!!!!!!!!!!!!!!!!!!Welcome To Our Server!!!!!!!!!!!!!!!!!!!!!!!'),nl,
write('**************Entertainment Package****************'),nl,
write(' #MENU'),nl,
write(' 1.Movies'),nl,
write(' 2.Songs'),nl,						
write(' 3.Dramas'),nl, 						
write(' 4.Series'),nl,						
write(' 5.Anime'),nl,
write(' 6.Exit'),nl,nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(X),
work(X).
work(X):- X>6,
write('Sorry invalid input'),nl,
write('write search for MENU').

work(X):- X==0,
write('Sorry invalid input'),nl,
write('write search for MENU').

work(1):-
write('1.Bangla'),nl,nl,
write('2.English'),nl,nl,
write('3.Hindi'),nl,nl,
write('4.Indian Bangla'),nl,nl,
write('@@@@@ Enter your choice @@@@@@@ : '),
read(Y),do(Y).

do(1):-
write('1.Aynabaji'),nl,
write('2.Monpura'),nl,
write('3.Shyamol chaya'),nl,
write('4.Television'),nl,
write('5.Krishno pokho'),nl,
write('6.Amar ache jol'),nl,
write('7.9no bipod songket'),nl,
write('8.Chandra kotha'),nl,
write('9.Srabon megher din'),nl,
write('10.Nandito norokey'),nl,         
write('11.Aguner poroshmoni'),nl,
write('12.Moner majhe'),nl,
write('13.Devdas'),nl,
write('14.Hazar bochor dhore'),nl,
write('15.Matir moyna'),nl,
write('16.Mukh o Mukhush'),nl,
write('17.Sangsar'),nl,
write('18.Sourani Duorani'),nl,
write('19.Moynamoti'),nl,
write('20.Neel akasher niche'),nl,
write('21.podma nodir majhi'),nl,
write('22.Odhikar'),nl,
write('23.Ghetu putro komola'),nl,
write('24.Tumi chuye dile mon'),nl,
write('25.Shasti'),nl,
write('26.Most Welcome'),nl,
write('27.Nirshartho valobasa'),nl,
write('28.Guerrilla'),nl,
write('29.Wrong number'),nl,
write('30.Bachelor'),nl,
write('31.Lal tip'),nl,
write('32.Dui duari'),nl,
write('33.Khoj the search'),nl,
write('34.Angar'),nl,
write('35.Bhola jay na tare'),nl,
write('36.Shikari'),nl,
write('37.Prem kahini'),nl,
write('38.Musafir'),nl,
write('39.Ice cream'),nl,
write('40.Ostitto'),nl,
write('41.Shankhachil'),nl,
write('42.One way'),nl,
write('43.Detective'),nl,
write('44.Rajneeti'),nl,
write('45.zero degree'),nl,
write('46.Agnee II'),nl,
write('47.Rajotto'),nl,
write('48.Ma er momota'),nl,
write('49.Taarkata'),nl,
write('50.Brihonnola'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(P),sel(P).

sel(P):-  P<51,P=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
sel(P):-  P>50,

write('Sorry invalid input'),nl,
write('Movie:'),nl,nl,
write('1.Bangla'),nl,nl,
write('2.English'),nl,nl,
write('3.Hindi'),nl,nl,
write('4.Indian Bangla'),nl,nl,
write('@@@@@ Enter your choice @@@@@@@ : '),
read(Y),do(Y).

sel(P):- P==0,
write('1.Most watched'),nl,
write('2.Most searched'),nl,
write('3.Trending'),nl, 
write('4.Recently added'),nl,
write('5.Recommendation'),nl,
write(' write new_option_1 for next:'),nl.
new_option_1:-
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(A),done(A).

done(1):-
write('1.Aynabaji'),nl,
write('2.Monpura'),nl,
write('3.Television'),nl,
write('4.9no bipod songket'),nl,
write('5.Moner majhe'),nl,
write('6.Tumi chuye dile mon'),nl,
write('7.Wrong number'),nl,
write('8.Bachelor'),nl,
write('9.Lal tip'),nl,
write('10.Khoj the search'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input'),nl.

choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~'),nl.

done(2):-
write('1.zero degree'),nl,
write('2.Agnee II'),nl,
write('3.Rajotto'),nl,
write('4.Ma er momota'),nl,
write('5.Taarkata'),nl,
write('6.Nirshartho valobasa'),nl,
write('7.Guerrilla'),nl,
write('8.Wrong number'),nl,
write('9.Bachelor'),nl,
write('10.Lal tip'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input'),nl.


choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~'),nl.
done(3):-
write('1.Aynabaji'),nl,
write('2.Monpura'),nl,
write('3.Shyamol chaya'),nl,
write('4.Television'),nl,
write('5.Krishno pokho'),nl,
write('6.Devdas'),nl,
write('7.Hazar bochor dhore'),nl,
write('8.Tumi chuye dile mon'),nl,
write('9.Shasti'),nl,
write('10.Most Welcome'),nl,

write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input'),nl.

choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~'),nl.
done(4):-
write('1.Aynabaji'),nl,
write('2.Monpura'),nl,
write('3.Shyamol chaya'),nl,
write('4.Television'),nl,
write('5.Krishno pokho'),nl,
write('6.Tumi chuye dile mon'),nl,
write('7.Shasti'),nl,
write('8.Most Welcome'),nl,
write('9.Nirshartho valobasa'),nl,
write('10.Guerrilla'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input'),nl.

choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~'),nl.
done(5):-
write('1.Aynabaji'),nl,
write('2.Television'),nl,
write('3.Chandra kotha'),nl,
write('4.Aguner poroshmoni'),nl,
write('5.Bachelor'),nl,
write('6.Tumi chuye dile mon'),nl,
write('7.Shasti'),nl,
write('8.Most Welcome'),nl,
write('9.Nirshartho valobasa'),nl,
write('10.Guerrilla'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input'),nl.
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~'),nl.
do(2):-
write('1. Artificial Intelligence'),nl, 
write('3.Spider-Man 3'),nl,
write('4. A Walk To Remember'),nl,
write('5.Happy Feet'),nl,
write('6.Star Wars: The Force Awakens'),nl,
write('7.Superman Returns'),nl,
write('8.The Pretty Woman'),nl,
write('9.Night at The Museum'),nl,
write('10.The Notebook'),nl,
write('11.Inside Out'),nl,
write('12.Titanic'),nl,
write('13.Captain America:Civil war'),nl,
write('14.Finding Dory'),nl,
write('15.Zootopia'),nl,
write('16.The Jungle Book'),nl,
write('17.Batman vs Supermoon: Dawn of justice'),nl,
write('18.Suicide Squad'),nl,
write('19.The Hangover'),nl,
write('20.Mission Impossible 3'),nl,
write('21.Jurassic World'),nl,
write('22.Furious 7'),nl,
write('23.Avengers: Age of Ultron'),nl,
write('24.Minions'),nl,
write('25.Spectre'),nl,
write('26.Mission Impossible-Rogue Nation'),nl,
write('27.The Hunger Games: Mockingijay-part2'),nl,
write('28.Transformers: Age of Exitinction'),nl,
write('29.Gurdians of The Galaxy'),nl,
write('30.Maleficent'),nl,
write('31.The Hunger Games: Mockingijay-part1'),nl,
write('32.X-Men: Days Of Future Past'),nl,
write('33.Captain America: The winter Soldier'),nl,
write('34.The Twilight Saga: New Moon'),nl,
write('35.The Amazing Spiderman'),nl,
write('36.Frozen'),nl,
write('37.Iron Man 3'),nl,
write('38.Despicable Me 2'),nl,
write('39.The Hunger Games: Catching Fire'),nl,
write('40.Fast & Furious 6'),nl,
write('41.Monsters University'),nl,
write('42.Gravity'),nl,
write('43.Man Of Steel'),nl,
write('44.Thor: The Dark world'),nl,
write('45.Avatar'),nl,
write('46.Harry Potter and the Half-Blood Prince'),nl,
write('47.Ice Age: Dawn of the Dinosaurs'),nl,
write('48.up'),nl,
write('49.Sherlock Homes'),nl,
write('50.Ratatouille'),nl,

write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(P),sell(P).
sell(P):-  P<51,P=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
sell(P):-  P>50,
write('Sorry invalid input'),nl.
write('Movie:'),nl,nl,
write('1.Bangla'),nl,nl,
write('2.English'),nl,nl,
write('3.Hindi'),nl,nl,
write('4.Indian Bangla'),nl,nl,
write('@@@@@ Enter your choice @@@@@@@ : '),
read(Y),do(Y).
sell(P):- P==0,
write('1.Most watched'),nl,
write('2.Most searched'),nl,
write('3.Trending'),nl, 
write('4.Recently added'),nl,
write('5.Recommendation'),nl,
write('write new_option_2 for next:'),nl.
new_option_2:-
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(B),do_ne(B).
do_ne(1):-
write('1.Spider-Man 3'),nl,
write('2. A Walk To Remember'),nl,
write('3.Superman Returns'),nl,
write('4.The Pretty Woman'),nl,
write('5.The Notebook'),nl,
write('6.Inside Out'),nl,
write('7.Titanic'),nl,
write('8.Furious 7'),nl,
write('9.Avengers: Age of Ultron'),nl,
write('10.Minions'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input'),nl.


choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~'),nl.
do_ne(2):-
write('1.Batman vs Supermoon: Dawn of justice'),nl,
write('2.Suicide Squad'),nl,
write('3.The Hangover'),nl,
write('4.Mission Impossible 3'),nl,
write('5.Jurassic World'),nl,
write('6.Furious 7'),nl,
write('7.Avengers: Age of Ultron'),nl,
write('8.Minions'),nl,
write('9.Frozen'),nl,
write('10.Iron Man 3'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input'),nl.

choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~~'),nl.
do_ne(3):-
write('1.Gravity'),nl,
write('2.Man Of Steel'),nl,
write('3.Thor: The Dark world'),nl,
write('4.Avatar'),nl,
write('5.Frozen'),nl,
write('6.up'),nl,
write('7.Sherlock Homes'),nl,
write('8.Transformers: Age of Exitinction'),nl,
write('9.Gurdians of The Galaxy'),nl,
write('10.Maleficent'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input'),nl.

choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~'),nl.
do_ne(4):-
write('1.Zootopia'),nl,
write('2.The Jungle Book'),nl,
write('3.Batman vs Supermoon: Dawn of justice'),nl,
write('4.Suicide Squad'),nl,
write('5.Maleficent'),nl,
write('6.Mission Impossible-Rogue Nation'),nl,
write('7.The Hunger Games: Mockingijay-part2'),nl,
write('8.Transformers: Age of Exitinction'),nl,
write('9.Gurdians of The Galaxy'),nl,
write('10.Maleficent'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input'),nl.

choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~'),nl.
do_ne(5):-
write('1.The Pretty Woman'),nl,
write('2.The Notebook'),nl,
write('3.Frozen'),nl,
write('4.Maleficent'),nl,
write('5.Titanic'),nl,
write('6.Mission Impossible-Rogue Nation'),nl,
write('7.The Hunger Games: Mockingijay-part2'),nl,
write('8.Transformers: Age of Exitinction'),nl,
write('9.Gurdians of The Galaxy'),nl,
write('10.Maleficent'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input'),nl.

choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~'),nl.
do(3):-
write('1.Highway'),nl,
write('2.Fan'),nl,
write('3.Tamasha'),nl,
write('4.Sarbjit'),nl,
write('5.Housefull 3'),nl,
write('6.Udta panjab'),nl,
write('7.Sultan'),nl,
write('8.Dishoom'),nl,
write('9.Kick'),nl, 
write('10.Bhoothnath Returns'),nl,
write('11.A Flying Jatt'),nl,
write('12.Akira'),nl,
write('13.Baar Baar Dekho'),nl,
write('14.Pink'),nl,
write('15.Ae dil hai Mushkkil'),nl,
write('16.Tutak Tutak Tutiya'),nl,
write('17.Rock ON 2'),nl,
write('18.Holiday'),nl,
write('19.Force 2'),nl,
write('20.Dear Zindegi'),nl, 
write('21.Action Jackson'),nl,
write('22.Bobby jasoos'),nl,
write('23.Badlapur'),nl,
write('24.Dum Laga ke Haisha'),nl,
write('25.Ek Villain'),nl, 
write('26.Gabbar Is Back'),nl,
write('27.Piku'),nl,
write('28.Haider'),nl, 
write('29.Tanu Weds Manu Returns'),nl,
write('30.Hamari Adhuri Kahani'),nl,
write('31. ABCD 2'),nl,
write('32.Baahubali'),nl,
write('33.Gulab Gang'),nl,
write('34.Drishyam'),nl,
write('35.All is Well'),nl,
write('36.Brothers'),nl, 
write('37.Welcome Back'),nl,
write('38.Rocky Handsome'),nl,
write('39.Heropanti'),nl, 
write('40.Singh is bliing'),nl,
write('41.Jazba'),nl,
write('42.Pyar Ka Punchnama2'),nl,
write('43.Queen'),nl,
write('44.2 states'),nl, 
write('45.Happy New year'),nl,
write('46.Bajirao Mastani'),nl,
write('47.Mary Kom'),nl, 
write('48.PK'),nl,
write('49.Hasee toh Phasee'),nl,
write('50.Khoobsurat'),nl,

write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(P),
sl(P).
sl(P):- P<51,P=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
sl(P):-  P>50,
write('Sorry invalid input'),nl,
write('Movie:'),nl,nl,

write('1.Bangla'),nl,nl,
write('2.English'),nl,nl,
write('3.Hindi'),nl,nl,
write('4.Indian Bangla'),nl,nl,
write('@@@@@ Enter your choice @@@@@@@ : '),
read(Y),do(Y).
sl(P):- P==0,
write('1.Most watched'),nl,
write('2.Most searched'),nl,
write('3.Trending'),nl, 
write('4.Recently added'),nl,
write('5.Recommendation'),nl,
write('write new_option_3:'),nl.
new_option_3:-
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(C),did(C).
did(1):-
write('1.Highway'),nl,
write('2.Fan'),nl,
write('3.Tamasha'),nl,
write('4.Sarbjit'),nl,
write('5.Housefull 3'),nl,
write('6.Sultan'),nl,
write('7.Dishoom'),nl,
write('8.Kick'),nl, 
write('9.Bhoothnath Returns'),nl,
write('10.Pink'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input'),nl.

choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~~'),nl.
did(2):-
write('1.Highway'),nl,
write('2.Tamasha'),nl,
write('3.Holiday'),nl,
write('4.Force 2'),nl,
write('5.Dear Zindegi'),nl, 
write('6.Action Jackson'),nl,
write('7. ABCD 2'),nl,
write('8.Baahubali'),nl,
write('9.Gulab Gang'),nl,
write('10.Drishyam'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').

choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~'),nl.
did(3):-
write('1.Highway'),nl,
write('2.Fan'),nl,
write('3.Tamasha'),nl,
write('4.Sarbjit'),nl,
write('5.Pink'),nl,
write('6.Ae dil hai Mushkkil'),nl,
write('7.Rock ON 2'),nl,
write('8.PK'),nl,
write('9.Hasee toh Phasee'),nl,
write('10.Khoobsurat'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~~'),nl.
did(4):-
write('1.Highway'),nl,
write('2.Fan'),nl,
write('3.Tamasha'),nl,
write('4.Sarbjit'),nl,
write('5.Housefull 3'),nl,
write('6.Bajirao Mastani'),nl,
write('7.Mary Kom'),nl, 
write('8.PK'),nl,
write('9.Hasee toh Phasee'),nl,
write('10.Khoobsurat'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):- Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~'),nl.
did(5):-
write('1.Highway'),nl,
write('2.Tamasha'),nl,
write('3.Force 2'),nl,
write('4.Piku'),nl,
write('5.Drishyam'),nl,
write('6.Bajirao Mastani'),nl,
write('7.Mary Kom'),nl, 
write('8.PK'),nl,
write('9.Hasee toh Phasee'),nl,
write('10.Khoobsurat'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~'),nl.
do(4):-
write('1.Baishe Shrabon'),nl,
write('2.Ekla Akash'),nl,
write('3.ChaderPahar'),nl,
write('4.Kanamachi'),nl,
write('5.Feluda'),nl,
write('6.Shankhachil'),nl,
write('7.Noukadubi'),nl,
write('8.Gupi Gain Bagha Bain'),nl,
write('9.Goyenda Gogol'),nl,
write('10.Chader Bari'),nl,
write('11.Chorabali'),nl,
write('12.Angaar'),nl,
write('13.Kelor Kirti'),nl,
write('14.Badsha'),nl,
write('15.Awara'),nl,
write('16.Prithibi Amare Chay'),nl,
write('17.Anondo Ashrom'),nl,
write('18.Moner Manush'),nl,
write('19.Aparajita Tumi'),nl,
write('20.Ghar Sangsar'),nl,
write('21.Autograph'),nl,
write('22.Aschey Shokal'),nl,
write('23.Chotobou'),nl,
write('24.Dui Prithibi'),nl,
write('25.Guru'),nl,
write('26.Hungama'),nl,
write('27.Debdut'),nl,
write('28.Mon Boleche Amar'),nl,
write('29.Love Express'),nl,
write('30.Challange'),nl,
write('31.Rangbaz'),nl,
write('32.Kelor Kirti'),nl,
write('33.Opekha'),nl,
write('34.Josh'),nl,
write('35.Sudhu Tomari Jonyo'),nl,
write('36.Songi'),nl,
write('37.Sathi'),nl,
write('38.Abhiman'),nl, 
write('39.Boss'),nl,
write('40.Bojhena se Bojhena'),nl,
write('41.Fade Poriya Boga Kandere'),nl,
write('42.Goynar Baksho'),nl,
write('43.Black'),nl,
write('44.Bangali Babu English Mam'),nl,
write('45.Mshor Rawhoshyo'),nl,
write('46.Dewana'),nl,
write('47.Romeo'),nl,
write('48.Majnu'),nl,
write('49.KakaBabu'),nl,
write('50.Premer Kahini'),nl,

write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(P),sl_l(P).
sl_l(P):-  P<51,P=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
sl_l(P):-  P>50,
write('Sorry invalid input'),nl,
write('Movie:'),nl,nl,
write('1.Bangla'),nl,nl,
write('2.English'),nl,nl,
write('3.Hindi'),nl,nl,
write('4.Indian Bangla'),nl,nl,
write('@@@@@ Enter your choice @@@@@@@ : '),
read(Y),do(Y)..
sl_l(P):- P==0,
write('write new_option_4:'),nl.
write('1.Most watched'),nl,
write('2.Most searched'),nl,
write('3.Trending'),nl, 
write('4.Recently added'),nl,
write('5.Recommendation'),nl.
new_option_4:-
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(D),di(D).
di(1):-
write('1.Baishe Shrabon'),nl,
write('2.Ekla Akash'),nl,
write('3.ChaderPahar'),nl,
write('4.Kanamachi'),nl,
write('5.Feluda'),nl,
write('6.Abhiman'),nl, 
write('7.Boss'),nl,
write('8.Bojhena se Bojhena'),nl,
write('9.Fade Poriya Boga Kandere'),nl,
write('10.Goynar Baksho'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):- Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~'),nl.
di(2):-
write('1.Feluda'),nl,
write('2.Shankhachil'),nl,
write('3.Noukadubi'),nl,
write('4.Gupi Gain Bagha Bain'),nl,
write('5.Goyenda Gogol'),nl,
write('6.Chader Bari'),nl,
write('7.Chorabali'),nl,
write('8.Guru'),nl,
write('9.Hungama'),nl,
write('10.Debdut'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~'),nl.
di(3):-
write('1.Kanamachi'),nl,
write('2.Feluda'),nl,
write('3.Shankhachil'),nl,
write('4.Noukadubi'),nl,
write('5.Gupi Gain Bagha Bain'),nl,
write('6.Goyenda Gogol'),nl,
write('7.Chorabali'),nl,
write('8.Majnu'),nl,
write('9.KakaBabu'),nl,
write('10.Premer Kahini'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~~~'),nl.
di(4):-
write('1.Baishe Shrabon'),nl,
write('2.Ekla Akash'),nl,
write('3.ChaderPahar'),nl,
write('4.Kanamachi'),nl,
write('5.Feluda'),nl,
write('6.Dewana'),nl,
write('7.Romeo'),nl,
write('8.Majnu'),nl,
write('9.KakaBabu'),nl,
write('10.Premer Kahini'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~'),nl.
di(5):-
write('1.Chorabali'),nl,
write('2.Angaar'),nl,
write('3.Autograph'),nl,
write('4.Aschey Shokal'),nl,
write('5.Chotobou'),nl,
write('6.Dewana'),nl,
write('7.Romeo'),nl,
write('8.Majnu'),nl,
write('9.KakaBabu'),nl,
write('10.Premer Kahini'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~'),nl.

work(2):-
write('1.Bangla'),nl,nl,
write('2.English'),nl,nl,
write('3.Hindi'),nl,nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Z),ch(Z).
ch(1):-
write('1.Amaro porano jaha chay'),nl,
write('2.Ami sunechi se din'),nl,
write('3.Coffe houser sei adda ta aj r nei'),nl,
write('4.Venge mor ghorer chabi'),nl,
write('5.Amar hiyar majhe'),nl,
write('6.Tumi boruna hole hobo ami sunil'),nl,
write('7.Ek paye nupu tomar'),nl,
write('8.Mey tumi akhno amay bondhu vabo ki'),nl,
write('9.Ekta gopon kotha chilo bolber'),nl,
write('10.Ekhn onek rat'),nl,
write('11.Megher pore'),nl,
write('12.Amar chip noukay esho'),nl,
write('13.Mey tui amare mitha sikhali'),nl,
write('14.Ei path jodi na sesh hoy'),nl,
write('15.Mon sudhu mon chuyeche'),nl,
write('16.Majhe majhe tomay vebe'),nl,
write('17.Dure tumi dariye'),nl,
write('18.Rodela dupure'),nl,
write('19.Kalponik prem'),nl,
write('20.Din bari jay'),nl,
write('21.Aj tomar mon kharap mey'),nl,
write('22.Se je boshe ache eka eka'),nl,
write('23.Jacho dure jao tumi'),nl,
write('24.Chai na mey tumi'),nl,
write('25.Reshmi churi'),nl,
write('26.Jhoom'),nl,
write('27.Meghomilon'),nl,
write('28.Shei meyeta'),nl,
write('29.Tomake chai'),nl,
write('30.Tumi amar ghum'),nl,
write('31.Tumi amar moner koner'),nl,
write('32.Jodi tor dak shune'),nl,
write('33.chokher aloy dekhechilam chokher bahire'),nl,
write('34.Bhebe bhebe boli'),nl,
write('35.Hyto tomari jonno hoyechi preme bonno'),nl,
write('36.Aj ai din ta ke moner khatay likhe rakho'),nl,
write('37.Alo alo'),nl,
write('38.Melay jai re'),nl,
write('39.pagla haoar badol din a'),nl,
write('40.Megh balika'),nl,
write('41.Gari chole na'),nl,
write('42.Bahir bole dure thako'),nl,
write('43.Ore nil doriya'),nl,
write('44.Onuvobe tumi'),nl,
write('45.Prem tumi'),nl,
write('46.Tomay ghire'),nl,
write('47.Tumi chaile bristi'),nl,
write('48.Bolchi shono'),nl,
write('49.Prematal'),nl,
write('50.Keu na januk'),nl,

write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(P),
sool(P).
sool(P):-  P<51,P=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
sool(P):-  P>50,
write('Sorry invalid input'),
write('Song:'),nl,nl,

write('1.Bangla'),nl,nl,
write('2.English'),nl,nl,
write('3.Hindi'),nl,nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Z),ch(Z).
sool(P):- P==0,
write('1.Most watched'),nl,
write('2.Most searched'),nl,
write('3.Trending'),nl, 
write('4.Recently added'),nl,
write('5.Recommendation'),nl,
write('write new_option_5:'),nl.
new_option_5:-
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(F),diid(F).
diid(1):-
write('1.Amaro porano jaha chay'),nl,
write('2.Ami sunechi se din'),nl,
write('3.Coffe houser sei adda ta aj r nei'),nl,
write('4.Venge mor ghorer chabi'),nl,
write('5.Amar hiyar majhe'),nl,
write('6.Tumi boruna hole hobo ami sunil'),nl,
write('7.Ek paye nupu tomar'),nl,
write('8.Mey tumi akhno amay bondhu vabo ki'),nl,
write('9.Ekta gopon kotha chilo bolber'),nl,
write('10.Ekhn onek rat'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~'),nl.
diid(2):-
write('1.Mey tumi akhno amay bondhu vabo ki'),nl,
write('2.Ekta gopon kotha chilo bolber'),nl,
write('3.Ekhn onek rat'),nl,
write('4.Megher pore'),nl,
write('5.Amar chip noukay esho'),nl,
write('6.Reshmi churi'),nl,
write('7.Jhoom'),nl,
write('8.Meghomilon'),nl,
write('9.Shei meyeta'),nl,
write('10.Tomake chai'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~'),nl.
diid(3):-
write('1.Amaro porano jaha chay'),nl,
write('2.Ami sunechi se din'),nl,
write('3.Coffe houser sei adda ta aj r nei'),nl,
write('4.Venge mor ghorer chabi'),nl,
write('5.Amar hiyar majhe'),nl,
write('6.Tumi boruna hole hobo ami sunil'),nl,
write('7.Ek paye nupu tomar'),nl,
write('8.Bolchi shono'),nl,
write('9.Prematal'),nl,
write('10.Keu na januk'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~'),nl.
diid(4):-
write('1.Amar hiyar majhe'),nl,
write('2.Tumi boruna hole hobo ami sunil'),nl,
write('3.Ek paye nupu tomar'),nl,
write('4.Mey tumi akhno amay bondhu vabo ki'),nl,
write('5.Ekta gopon kotha chilo bolber'),nl,
write('6.Tumi boruna hole hobo ami sunil'),nl,
write('7.Ek paye nupu tomar'),nl,
write('8.Bolchi shono'),nl,
write('9.Prematal'),nl,
write('10.Keu na januk'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~'),nl.
diid(5):-
write('1.Melay jai re'),nl,
write('2.pagla haoar badol din a'),nl,
write('3.Megh balika'),nl,
write('4.Gari chole na'),nl,
write('5.Bahir bole dure thako'),nl,
write('If you are confused press 0 for Help'),nl,
write('6.Tumi boruna hole hobo ami sunil'),nl,
write('7.Ek paye nupu tomar'),nl,
write('8.Bolchi shono'),nl,
write('9.Prematal'),nl,
write('10.Keu na januk'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~'),nl.
ch(2):-
write('1.The Long And Winding Road'),nl,
write('2.With a Little Help From My Friends'),nl,
write('3.From Me To You'),nl,
write('4.Love Me Do'),nl,
write('5.I’ll Follow The Sun'),nl,
write('6.She Loves You'),nl,
write('7.Can’t Buy Me Love'),nl,
write('8.Eight Days A Week'),nl,
write('9.I Want To Hold Your Hand'),nl,
write('10.All You Need Is Love'),nl,
write('11.Paradise'),nl,
write('12.Viva La Vida'),nl,
write('13.Fix You'),nl,
write('14.Princess Of China'),nl,
write('15.Yellow'),nl,
write('16.How Can I Stop'),nl,
write('17.Let Me Go'),nl,
write('18.Slave'),nl,
write('19.Mother\'s Little Helper'),nl,
write('20.Fingerprint File'),nl,
write('21.Monkey Man'),nl,
write('22.Heaven '),nl,
write('23.Let It Loose'),nl,
write('24.Love in Vain '),nl,
write('25.When the Whip Comes Down'),nl,
write('26.Backstreet Girl'),nl,
write('27.Rough Justice '),nl,
write('28.Roll With It '),nl,
write('29.Whatever'),nl,
write('30.D’You Know What I Mean'),nl,
write('31.Don’t Look Back In Anger '),nl,
write('32.Wonderwall'),nl,
write('33.Astronomy Domine '),nl,
write('34.Have a Cigar '),nl,
write('35.Brain Damage'),nl,
write('36.Echoes'),nl,
write('37.Boris the Spider'),nl,
write('38.Relax '),nl,
write('39.Another Tricky Day '),nl,
write('40.Going Mobile'),nl,
write('41.Overture'),nl,
write('42.Bargain'),nl,
write('43.Trick of the Light '),nl,
write('44.Let\'s See Action'),nl,
write('45.Young Man Blues'),nl,
write('46.Heaven and Hell'),nl,
write('47.I’m the Boy'),nl,
write('48.Who loves you a lot'),nl,
write('49.But can’t reach you'),nl,
write('50.The Acid Queen'),nl,

write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(P),
rr(P).
rr(P):-  P<51,P=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
rr(P):-  P>50,
write('Sorry invalid input'),nl,
write('Song:'),nl,nl,

write('1.Bangla'),nl,nl,
write('2.English'),nl,nl,
write('3.Hindi'),nl,nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Z),ch(Z).
rr(P):- P==0,
write('1.Most watched'),nl,
write('2.Most searched'),nl,
write('3.Trending'),nl, 
write('4.Recently added'),nl,
write('5.Recommendation'),nl,
write('write new_option_6:'),nl.
new_option_6:-
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(T),rr1(T).
rr1(1):-
write('1.The Long And Winding Road'),nl,
write('2.With a Little Help From My Friends'),nl,
write('3.From Me To You'),nl,
write('4.Love Me Do'),nl,
write('5.I’ll Follow The Sun'),nl,
write('6.She Loves You'),nl,
write('7.Can’t Buy Me Love'),nl,
write('8.Eight Days A Week'),nl,
write('9.I Want To Hold Your Hand'),nl,
write('10.All You Need Is Love'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~'),nl.
rr1(2):-
write('1.Can’t Buy Me Love'),nl,
write('2.Eight Days A Week'),nl,
write('3.I Want To Hold Your Hand'),nl,
write('4.All You Need Is Love'),nl,
write('5.Paradise'),nl,
write('6.Viva La Vida'),nl,
write('7.Fix You'),nl,
write('8.Princess Of China'),nl,
write('9.Yellow'),nl,
write('10.How Can I Stop'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~'),nl.
rr1(3):-
write('1.All You Need Is Love'),nl,
write('2.Paradise'),nl,
write('3.Viva La Vida'),nl,
write('4.Fix You'),nl,
write('5.Princess Of China'),nl,
write('6.Yellow'),nl,
write('7.How Can I Stop'),nl,
write('8.Who loves you a lot'),nl,
write('9.But can’t reach you'),nl,
write('10.The Acid Queen'),nl,

write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~'),nl.
rr1(4):-
write('1.Fix You'),nl,
write('2.Princess Of China'),nl,
write('3.Yellow'),nl,
write('4.How Can I Stop'),nl,
write('5.Let Me Go'),nl,
write('6.Yellow'),nl,
write('7.How Can I Stop'),nl,
write('8.Who loves you a lot'),nl,
write('9.But can’t reach you'),nl,
write('10.The Acid Queen'),nl,

write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~'),nl.
rr1(5):-
write('1.The Long And Winding Road'),nl,
write('2.With a Little Help From My Friends'),nl,
write('3.From Me To You'),nl,
write('4.Love Me Do'),nl,
write('5.I’ll Follow The Sun'),nl,
write('6.Yellow'),nl,
write('7.How Can I Stop'),nl,
write('8.Who loves you a lot'),nl,
write('9.But can’t reach you'),nl,
write('10.The Acid Queen'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~~'),nl.

ch(3):-
write('1.Ladki Beautiful'),nl,
write('2.Ude Dil befikre'),nl,
write('3.Love Is a Dare'),nl,
write('4.You And Me'),nl,
write('5.Labon Ka Karobaar'),nl,
write('6.Befikre'),nl,
write('7.High Heels'),nl,
write('8.Most Wanted Munda'),nl,
write('9.Ae dil hai mushkil'),nl,
write('10.Channa Mereya'),nl,
write('11.The Break up song'),nl,
write('12.Kabhi Kabhi Mere Dil Me'),nl,
write('13.Tu Mera Hero '),nl,
write('14.Aaur Main Kush hoon'),nl,
write('15.Lamhon ke Rasgulle'),nl,
write('16.Wajah Tum Ho.'),nl,
write('17.Dil Ke Pas'),nl,
write('18.Mahi Ve'),nl,
write('19.Rang Laal'),nl,
write('20.O Janiya'),nl,
write('21.Catch Me If You Can'),nl,
write('22.Ishaara'),nl,
write('23.Dekh Lena'),nl,
write('24.Teri Fariyad'),nl,
write('25.Tum Bin'),nl,
write('26.Masta'),nl,
write('27.Love You Zindegi'),nl,
write('28.Just Go To Hell Dil'),nl,
write('29.Lets Break Up'),nl,
write('30.Rock On'),nl,
write('31.Tere Mere Dil'),nl,
write('32.Chal Maar'),nl,
write('33.Chalte Chalte'),nl,
write('34.A Flying jatt'),nl,
write('35.Toota Jo Kabhi Tara'),nl,
write('36.Kala Chashma'),nl,
write('37.Sau Aasmaan'),nl,
write('38.Rajj Rajj Ke'),nl,
write('39.Sultan'),nl,
write('40.Baby Ko Bass Pasand Hein'),nl,
write('41.440 Volt'),nl,
write('42.Sau tarah ke '),nl,
write('43.Janeman Aah'),nl,
write('44.Tere Sang Yara'),nl,
write('45.Tu Hai'),nl,
write('46.Pyaar ki'),nl,
write('47.Taang Uthake'),nl,
write('48.Dard'),nl,
write('49.Sab Tera'),nl,
write('50.Cham Cham'),nl,

write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(P),
si(P).
si(P):-  P<51,P=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
si(P):-  P>50,
write('Sorry invalid input'),nl,
write('Song:'),nl,nl,

write('1.Bangla'),nl,nl,
write('2.English'),nl,nl,
write('3.Hindi'),nl,nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Z),ch(Z).
si(P):- P==0,
write('1.Most watched'),nl,
write('2.Most searched'),nl,
write('3.Trending'),nl, 
write('4.Recently added'),nl,
write('5.Recommendation'),nl,
write('write new_option_7:'),nl.
new_option_7:-
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(G),dd(G).
dd(1):-
write('1.Ladki Beautiful'),nl,
write('2.Ude Dil befikre'),nl,
write('3.Love Is a Dare'),nl,
write('4.You And Me'),nl,
write('5.Labon Ka Karobaar'),nl,
write('6.Befikre'),nl,
write('7.High Heels'),nl,
write('8.Most Wanted Munda'),nl,
write('9.Ae dil hai mushkil'),nl,
write('10.Channa Mereya'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~'),nl.
dd(2):-
write('1.Ladki Beautiful'),nl,
write('2.High Heels'),nl,
write('3.Ae dil hai mushkil'),nl,
write('4.The Break up song'),nl,
write('5.Kabhi Kabhi Mere Dil Me'),nl,
write('6.Tu Mera Hero '),nl,
write('7.Aaur Main Kush hoon'),nl,
write('8.Lamhon ke Rasgulle'),nl,
write('9.Wajah Tum Ho.'),nl,
write('10.Dil Ke Pas'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~'),nl.
dd(3):-
write('1.Mahi Ve'),nl,
write('2.Rang Laal'),nl,
write('3.O Janiya'),nl,
write('4.Ladki Beautiful'),nl,
write('5.High Heels'),nl,
write('6.Ae dil hai mushkil'),nl,
write('7.The Break up song'),nl,
write('8.Dard'),nl,
write('9.Sab Tera'),nl,
write('10.Cham Cham'),nl,

write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~'),nl.
dd(4):-
write('1.Ladki Beautiful'),nl,
write('2.High Heels'),nl,
write('3.The Break up song'),nl,
write('4.Tu Mera Hero '),nl,
write('5.Wajah Tum Ho.'),nl,
write('6.Pyaar ki'),nl,
write('7.Taang Uthake'),nl,
write('8.Dard'),nl,
write('9.Sab Tera'),nl,
write('10.Cham Cham'),nl,

write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~'),nl.
dd(5):-
write('1.Ladki Beautiful'),nl,
write('2.High Heels'),nl,
write('3.The Break up song'),nl,
write('4.Tu Mera Hero '),nl,
write('5.Wajah Tum Ho.'),nl,
write('6.Pyaar ki'),nl,
write('7.Taang Uthake'),nl,
write('8.Dard'),nl,
write('9.Sab Tera'),nl,
write('10.Cham Cham'),nl,

write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~~'),nl.
work(3):-
write('1.Mr&Mrs'),nl,
write('2.Maya Kanna'),nl,
write('3.Gopal var'),nl,
write('4.Anur Abacus'),nl,
write('5.Tiger vai'),nl,
write('6.Pocket Mar'),nl,
write('7.After Marriage'),nl,
write('8.Metro Life'),nl,
write('9.Holud Ronger Baina'),nl,
write('10.Tomay Valobeshe'),nl,
write('11.Old is Gold'),nl,
write('12.Valobasar Pongktimala'),nl,
write('13.Tai Tomake'),nl,
write('14.Off Beat'),nl,
write('15.Revision'),nl,
write('16.Selfiebaz'),nl,
write('17.Angry Bird'),nl,
write('18.Priotomeshu'),nl,
write('19.Kothopokothon'),nl,
write('20.Amader Golpo'),nl,
write('21.Story of Thousand Days'),nl,
write('22.Rupkotha Ekhon Ay Hoy Na'),nl,
write('23.Monsuba'),nl,
write('24.Love Lane'),nl,
write('25.Haat ta Dao Na Bariye '),nl,
write('26.Nilpori Nilanjana'),nl,
write('27.Love and War'),nl,
write('28.Keu Na Januk'),nl,
write('29.Tumimoy'),nl,
write('30.Anamika'),nl,
write('31.Valobashi Tai Valobeshe Jai'),nl,
write('32.Valobasha 101'),nl,
write('33.Ei Poth Jodi Na Sesh Hoy'),nl,
write('34.Tomay Vebe Lekha'),nl,
write('35.Chinigura Prem'),nl,
write('36.Kichu Vul Kichu Oviman'),nl,
write('37.Prem Keboli Ekti Rashayonik Bikriya') ,nl,
write('38.Prem Kora Biya'),nl,
write('39.Kotha Bondhu Mithila'),nl,
write('40.Dritir Baire'),nl,
write('41.Maya'),nl,
write('42.Projapotir Kosto'),nl,
write('43.Se Rate Bristi Cilo '),nl,
write('44.Tomar Amar'),nl,
write('45.Sei Meyeta'),nl,
write('46.Ditio Matra'),nl,
write('47.Sikandar Box'),nl,
write('48.Arman Vai Faisa Gese'),nl,
write('49.Mon Foringer Golpo'),nl,
write('50.To Airport'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(P),
sol(P).
sol(P):-  P<51,P=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
sol(P):-  P>50,
write('Sorry invalid input'),nl,
write('write search for MENU').

sol(P):- P==0,
write('1.Most watched'),nl,
write('2.Most searched'),nl,
write('3.Trending'),nl, 
write('4.Recently added'),nl,
write('5.Recommendation'),nl,
write('write new_option_8:'),nl.
new_option_8:-
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(E),dii(E).
dii(1):-
write('1.Mr&Mrs'),nl,
write('2.Sei Meyeta'),nl,
write('3.Sikandar Box'),nl,
write('4.Arman Vai Faisa Gese'),nl,
write('5.Mon Foringer Golpo'),nl,
write('6.Valobasi tai valobese jai'),nl,
write('7.Tai Tomake'),nl,
write('8.Off Beat'),nl,
write('9.Revision'),nl,
write('10.Selfiebaz'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~'),nl.
dii(2):-
write('1.Tai Tomake'),nl,
write('2.Off Beat'),nl,
write('3.Revision'),nl,
write('4.Selfiebaz'),nl,
write('5.Angry Bird'),nl,
write('6.Prem Kora Biya'),nl,
write('7.Kotha Bondhu Mithila'),nl,
write('8.Dritir Baire'),nl,
write('9.Maya'),nl,
write('10.Projapotir Kosto'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~'),nl.
dii(3):-
write('1.Mr&Mrs'),nl,
write('2.Sei Meyeta'),nl,
write('3.Sikandar Box'),nl,
write('4.Arman Vai Faisa Gese'),nl,
write('5.Mon Foringer Golpo'),nl,
write('6.Selfiebaz'),nl,
write('7.Angry Bird'),nl,
write('8.Keu Na Januk'),nl,
write('9.Tumimoy'),nl,
write('10.Anamika'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~'),nl.
dii(4):-
write('1.Selfiebaz'),nl,
write('2.Angry Bird'),nl,
write('3.Chinigura Prem'),nl,
write('4.Kichu Vul Kichu Oviman'),nl,
write('5.Prem Keboli Ekti Rashayonik Bikriya') ,nl,
write('6.Nilpori Nilanjana'),nl,
write('7.Love and War'),nl,
write('8.Keu Na Januk'),nl,
write('9.Tumimoy'),nl,
write('10.Anamika'),nl,
write('If you are confused press zero for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~'),nl.
dii(5):-
write('1.Mr&Mrs'),nl,
write('2.Angry Bird'),nl,
write('3.Selfiebaz'),nl,
write('4.Rupkotha Ekhon Ay Hoy Na'),nl,
write('5.Monsuba'),nl,
write('6.Nilpori Nilanjana'),nl,
write('7.Love and War'),nl,
write('8.Keu Na Januk'),nl,
write('9.Tumimoy'),nl,
write('10.Anamika'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~'),nl.
work(4):-
write('1.Game Of Thrones'),nl,           
write('2.The Big Bang Theory'),nl,
write('3.How I Met Your Mother'),nl,
write('4.Sherlock'),nl,                       
write('5.Palace'),nl,                 
write('6.Dexter'),nl,
write('7.FRIENDS'),nl,
write('8.Two & a Half Man'),nl,
write('9.Grey-s Anatomy'),nl,
write('10.One Tree Hill'),nl,
write('11.Dollhouse'),nl,
write('12.Quantico'),nl,                    
write('13.The Vampire Diaries'),nl,                    
write('14.The X Files'),nl,
write('15.Two Broke Girls'),nl,
write('16.Scrubs'),nl,
write('17.White Collar'),nl,
write('18.House'),nl,
write('19.Heroes'),nl,
write('20.Desperate Housewives'),nl,
write('21.The Wonder Years'),nl,
write('22.The Simpsons'),nl,
write('23.Mr. Bean'),nl,
write('24.Miranda'),nl,
write('25.Get Smart'),nl,
write('26.The Thin Blue Line'),nl,
write('27.The Good Life'),nl,
write('28.The Royal Family'),nl,
write('29.The Office'),nl,
write('30.Top Gear'),nl,
write('31.Black Books'),nl,
write('32.Episodes'),nl,
write('33.Black Mirror'),nl,
write('34.Humans'),nl,
write('35.The Last Kingdom'),nl,
write('36.Life On Mars'),nl,
write('37.Happy Vallay'),nl,
write('38.Spy'),nl,
write('39.The Fall'),nl,
write('40.The Honourable Woman'),nl,
write('41.An Idoit Abroad'),nl,
write('42.The Missing'),nl,
write('43.Family Guy'),nl,
write('44.Freaks And Geeks'),nl,
write('45.Revenge'),nl,
write('46.Boston Leagal'),nl,
write('47.The Practice'),nl,
write('48.Murder One'),nl,
write('49.Mattlock'),nl,
write('50.The Defenders'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(P),s_l(P).
s_l(P):-  P<51,P=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
s_l(P):-  P>50,
write('Sorry invalid input'),nl,
write('write search for MENU').
s_l(P):- P==0,
write('1.Most watched'),nl,
write('2.Most searched'),nl,
write('3.Trending'),nl, 
write('4.Recently added'),nl,
write('5.Recommendation'),nl,
write('writ new_option_9:'),nl.
new_option_9:-

write(' @@@@@ Enter your choice @@@@@@@ : '),
read(K),wk(K).
wk(1):-
write('1.Game Of Thrones'),nl,           
write('2.The Big Bang Theory'),nl,
write('3.How I Met Your Mother'),nl,
write('4.Sherlock'),nl,                       
write('5.Palace'),nl,                 
write('6.Dexter'),nl,
write('7.FRIENDS'),nl,
write('8.Two & a Half Man'),nl,
write('9.Grey-s Anatomy'),nl,
write('10.One Tree Hill'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~'),nl.
wk(2):-
write('1..How I Met Your Mother'),nl,
write('2.Sherlock'),nl,                       
write('3.Palace'),nl,                 
write('4.Dexter'),nl,
write('5.FRIENDS'),nl,
write('6.Two & a Half Man'),nl,
write('7.Grey-s Anatomy'),nl,
write('8.One Tree Hill'),nl,
write('9.Dollhouse'),nl,
write('10.Quantico'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~'),nl.
wk(3):-                    
write('1.The Vampire Diaries'),nl,                    
write('2.The X Files'),nl,
write('3.Two Broke Girls'),nl,
write('4.Scrubs'),nl,
write('5.White Collar'),nl,
write('6.Game Of Thrones'),nl,           
write('7.The Big Bang Theory'),nl,
write('8.Murder One'),nl,
write('9.Mattlock'),nl,
write('10.The Defenders'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~'),nl.
wk(4):-
write('1.Game Of Thrones'),nl,           
write('2.The Big Bang Theory'),nl,
write('3.How I Met Your Mother'),nl,
write('4.Sherlock'),nl,                       
write('5.Palace'),nl,  
write('6.Game Of Thrones'),nl,           
write('7.The Big Bang Theory'),nl,
write('8.Murder One'),nl,
write('9.Mattlock'),nl,
write('10.The Defenders'),nl, 
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~'),nl.
wk(5):-
write('1.Game Of Thrones'),nl,           
write('2.The Big Bang Theory'),nl,
write('3.How I Met Your Mother'),nl,
write('4.Dollhouse'),nl,
write('5.Quantico'),nl,
write('6.Game Of Thrones'),nl,           
write('7.The Big Bang Theory'),nl,
write('8.Murder One'),nl,
write('9.Mattlock'),nl,
write('10.The Defenders'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~'),nl.
work(5):-
write('1.Pokemon'),nl,
write('2.Dragon Ball'),nl,
write('3.Shakugan No Shana'),nl,
write('4.Stigma Of The Wind'),nl,
write('5.Fairy Tail'),nl,
write('6.Tokyo Ghoul'),nl,
write('7.Akame Ga Kill'),nl,
write('8.Fate Stay Night'),nl,
write('9.Noragami'),nl,
write('10.Assassination Classroom'),nl,
write('11.Death Note'),nl,
write('12.Otaku Teacher'),nl,
write('13.Tokyo Ravens'),nl,
write('14.Sereph Of The End Vampire Reign'),nl,
write('15.Twin Star Exorcists'),nl,
write('16.Lucky Star'),nl,
write('17.Blue Exorcist'),nl,
write('18.Sword Art Online'),nl,
write('19.The Devil Is A Part Timer'),nl,
write('20.Beyond The Boundary'),nl,
write('21.Black Butler'),nl,
write('22.Code Geass'),nl,
write('23.K Project'),nl,
write('24.Naruto'),nl,
write('25.Another'),nl,
write('26.The 7 Deadly Sins'),nl,
write('27.Blood Blockade Battlefront'),nl,
write('28.Doraemon'),nl,
write('29.Psycho Pass'),nl,
write('30.One Punch '),nl,
write('31.Attack On Titan'),nl,
write('32.Sinchan'),nl,
write('33.Angel Beats'),nl,
write('34.Soul Eater'),nl,
write('35.Samurai Champloo'),nl,
write('36.Inuyasha'),nl,
write('37.Guilty Crown'),nl,
write('38.Hellsing'),nl,
write('39.Bleach'),nl,
write('40.Full Metal Alchemist'),nl,
write('41.One Piece'),nl,
write('42.Cowboy Bebhop'),nl,
write('43.Inazuma Eleven'),nl,
write('44.Bayblade'),nl,
write('45.Hunter X Hunter'),nl,
write('46.Gintama'),nl,
write('47.Cardfight Vanguard'),nl,
write('48.Your Lie In April'),nl,
write('49.Digimon'),nl,
write('50.Prince Of Stride'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(P),
ssel(P).
ssel(P):-  P<51,P=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
ssel(P):-  P>50,
write('Sorry invalid input'),nl,
write('write search for MENU').
ssel(P):- P==0,

write('1.Most watched'),nl,
write('2.Most searched'),nl,
write('3.Trending'),nl, 
write('4.Recently added'),nl,
write('5.Recommendation'),nl,
write('write new_option_10 for help:'),nl.
new_option_10:-
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(J),wk1(J).

wk1(1):-
write('1.Pokemon'),nl,
write('2.Dragon Ball'),nl,
write('3.Shakugan No Shana'),nl,
write('4.Stigma Of The Wind'),nl,
write('5.Fairy Tail'),nl,
write('6.Tokyo Ghoul'),nl,
write('7.Akame Ga Kill'),nl,
write('8.Fate Stay Night'),nl,
write('9.Noragami'),nl,
write('10.Assassination Classroom'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input'),nl,

choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~'),nl.
wk1(2):-
write('1.Pokemon'),nl,
write('2.Dragon Ball'),nl,
write('3.Shakugan No Shana'),nl,
write('4.Stigma Of The Wind'),nl,
write('5.Fairy Tail'),nl,
write('6.Tokyo Ghoul'),nl,
write('7.Akame Ga Kill'),nl,
write('8.Fate Stay Night'),nl,
write('9.Noragami'),nl,
write('10.Assassination Classroom'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~'),nl.
wk1(3):-
write('1.Tokyo Ghoul'),nl,
write('2.Akame Ga Kill'),nl,
write('3.Fate Stay Night'),nl,
write('4.Noragami'),nl,
write('5.Assassination Classroom'),nl,
write('6.Death Note'),nl,
write('7.Otaku Teacher'),nl,
write('8.Your Lie In April'),nl,
write('9.Digimon'),nl,
write('10.Prince Of Stride'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~~~'),nl.
wk1(4):-
write('1.Lucky Star'),nl,
write('2.Blue Exorcist'),nl,
write('3.Sword Art Online'),nl,
write('4.The Devil Is A Part Timer'),nl,
write('5.Beyond The Boundary'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~~~~'),nl.
wk1(5):-
write('1.Pokemon'),nl,
write('2.Dragon Ball'),nl,
write('3.Shakugan No Shana'),nl,
write('4.Stigma Of The Wind'),nl,
write('5.Fairy Tail'),nl,
write('6.Death Note'),nl,
write('7.Otaku Teacher'),nl,
write('8.Your Lie In April'),nl,
write('9.Digimon'),nl,
write('10.Prince Of Stride'),nl,
write('If you are confused press 0 for Help'),nl,
write(' @@@@@ Enter your choice @@@@@@@ : '),
read(Q),choose(Q).
choose(Q):-  Q<11,Q=\=0,
write('~~~~~~~~~~~Enjoy Your Choice~~~~~~~~~~~~~~~~').
choose(Q):-  Q>10,
write('Sorry invalid input').
choose(Q):- Q==0,
write('Go back to MENU'),nl,
write('write search for MENU'),nl,
write('~~~~~~~~~~~~~~~~~THANK YOU~~~~~~~~~~~~~~~~~~~~'),nl.
work(6):-
write('Thanks for visiting our server'),nl,
write('!!!!!!!!!!!!!!!!!Share Your Experience!!!!!!!!!!!!!!!!'),nl,

read(T).